ekf_filter_node:
    ros__parameters:
        frequency: 30.0
        two_d_mode: true
        publish_tf: true
        map_frame: map
        odom_frame: odom
        base_link_frame: base_link
        world_frame: odom

        # ---------------- IMU Input ----------------
        imu0: /imu
        imu0_config: [false, false, false, # X Y Z
                      true,  true,  true,  # R P Y
                      false, false, false, # dX dY dZ
                      true,  true,  true,  # dR dP dY
                      true,  true,  true]  # ddX ddY ddZ
        imu0_differential: false
        imu0_relative: true
        imu0_queue_size: 10
        imu0_remove_gravitational_acceleration: true

        # ---------------- LiDAR Odometry Input ----------------
        odom0: /lidar_odom
        odom0_config: [true,  true,  false, # X Y Z
                       false, false, true,  # R P Y
                       true,  true,  false, # dX dY dZ
                       false, false, true,  # dR dP dY
                       false, false, false] # ddX ddY ddZ
        odom0_differential: false
        odom0_queue_size: 10

        # ---------------- Optical Flow Twist Input ----------------
        twist0: /optical_flow_twist
        twist0_config: [false, false, false,
                        false, false, false,
                        true,  true,  false,
                        false, false, false,
                        false, false, false]
        twist0_queue_size: 10

        use_control: false
